version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:root
  mongo-express:
    image: mongo-express
    restart: alawys
    ports:
      - 8081:8081
    environment:  
      - ME_CONFIG_MONGODB_ADMINUSERNAME:root
      - ME_CONFIG_MONGODB_ADMINPASSWORD:root
      - ME_CONFIG_MONGODB_URL:mongodb://root:root@mongo:27017/
  redis:
    image: redis
    container_name: redis 
    restart: unless-stopped
    # network_mode: bridge
    networks:
      - app-network
    ports:
      - 6379:6379/tcp
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  app-network:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge